# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cxwangyi/gotorch

    working_directory: /go/src/github.com/wangkuiyi/gotorch
    steps:
      - checkout
      - run: pre-commit run -a
      - run: cgotorch/build.sh
      - run: go get -v -t -d ./...
      - run: export LD_LIBRARY_PATH=$CIRCLE_WORKING_DIRECTORY/cgotorch/libtorch/lib:$LD_LIBRARY_PATH
      - run: OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run: bash <(curl -s https://codecov.io/bash)
      - run: cd benchmark; make; OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 ./mnist
