# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: gotorch/gotorch

    working_directory: /go/src/github.com/wangkuiyi/gotorch
    steps:
      - checkout
      - run: pre-commit run -a
      - run: LD_LIBRARY_PATH=$CIRCLE_WORKING_DIRECTORY/cgotorch/libtorch/lib
      - run: go generate ./...
      - run: go install ./...
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run: bash <(curl -s https://codecov.io/bash)
